name: C/C++ CI

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: check the directory
      run: ls
    - name: check 
      run: cd ../../; ls
    - name: run file
      run: gcc ../../code.c -o code; ./code

